name: researchcodes
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # notebooks
  - jupyterlab
  - ipykernel

  # core scientific stack
  - numpy
  - scipy
  - pandas
  - matplotlib

  # astronomy stack (按你需求可删减)
  - astropy
  - astroquery

  # dev tools
  - pytest
  - pre-commit
  - ruff

  # generating standard star catalog
  - pytables
  - astropy-healpix

  # optional: nice-to-have
  - rich
  - tqdm

  # generating observation calendar events
  - astroplan
  - icalendar
